name: Workflow

on:
  push:
    branches:
    - master

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: gahantognoli
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        tags: gahantognoli/fiap-ghactions:latest
        push: true
        
          
              
